project_id = "cqcklvdblhcdowisjnsf"

[functions.mpesa-stk-push]
verify_jwt = true

[functions.mpesa-callback]
verify_jwt = false

[functions.check-payment-status]
verify_jwt = true

[functions.pesapal-callback]
verify_jwt = false

[functions.pesapal-ipn-listener]
verify_jwt = false

[functions.pesapal-initiate-payment]
verify_jwt = true

[functions.pesapal-register-ipn]
verify_jwt = true

[functions.intasend-webhook]
verify_jwt = false